### PR TITLE
Port tracing fields to new names

### LINKED ISSUE #34: Emit Beeline fields instead of Zipkin model fields
Then at least theoretically you could intermingle Beelines and OT Proxy in the same dataset.

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/honeycombio/honeycomb-opentracing-proxy/issues/34

⚠️ BREAKING CHANGE ⚠️ 

I will sketch up a plan to notify users who might potentially update their proxy if this is merged.

This should provide compatibility with Beeline fields and OpenCensus emitted fields.

### CODE REVIEW

**Review by akvanhar — APPROVED** [review]
Looking forward to the release plan.

**Comment by akvanhar** [comment]
I wonder if there is a way where we could set a flag when running the proxy which specifies which mapping to use - Zipkin Mapping or Honeycomb Mapping.

**Review by maplebed — CHANGES_REQUESTED** [review]
I agree with @akvanhar's comment; this should be a setting in config. Please make it possible to choose which naming convention you'd like and then it won't be a breaking change and merging will be easy.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.

**Pull request closed without merging**
